### ISSUE TITLE
Some songs are not playing.

### ISSUE THREAD

**Issue by Klozer-app** [AssassinAguilar/AssassinAguilar#1]
Hi Jigyasu.  Awesome project,

**Comment by AssassinAguilar** [comment]
Hi @Klozer-app, Can you specify the problems happening or the extension of the file which are not playing. By the way, I suppose this issue is for [Wavy Beats](https://github.com/AssassinAguilar/WavyBeats). So please open it [here](https://github.com/AssassinAguilar/WavyBeats/issues)
Thank you 😊
